apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: camera-01
  namespace: kubeedge
  labels:
    model: camera-model
spec:
  deviceModelRef:
    name: camera-model
  nodeName: kubeedge-edge01
  properties:
    - name: status
      collectCycle: 10000
    - name: motionDetected
      collectCycle: 10000
    - name: frameCount
      collectCycle: 10000
    - name: confidence
      collectCycle: 10000
