apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camera-device
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/enriquesoto/kubeedge-gitops.git
    targetRevision: main
    path: manifests/camera-device
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeedge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
