grpc_server:
  socket_path: /etc/kubeedge/videosim.sock
common:
  name: Videosim-mapper
  version: v1.13.0
  api_version: v1.0.0
  protocol: videosim
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
